---
sudo: false
language: ruby
cache: bundler
script: 'bundle exec rake release_checks'
#Inserting below due to the following issue: https://github.com/travis-ci/travis-ci/issues/3531#issuecomment-88311203
before_install:
  - gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    dist: trusty
    env:
      # - USERNAME='WhatsARanjit'
      - PUPPET_VERSION=4.10.4
    script: bundle exec rake beaker
    sudo: required
notifications:
  email: false
