---
sudo: false
language: ruby
cache: bundler
script: "bundle exec rake release_checks"
before_install:
  - gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    dist: trusty
    env:
#     - USERNAME=WhatsARanjit
      - BEAKER_set=docker/centos-7
    script: bundle exec rake beaker
    services: docker
    sudo: required
notifications:
  email: false
