---
sudo: false
language: ruby
cache: bundler
before_install:
  - gem update bundler
matrix:
  include:
    - rvm: '2.1.9'
      dist: trusty
      env:
      # - USERNAME='WhatsARanjit'
        - PUPPET_VERSION=4.10.4 BEAKER_debug=true
      script:
        - 'bundle exec rake beaker'
