---
sudo: false
language: ruby
cache: bundler
dist: trusty
before_install:
  # https://github.com/travis-ci/travis-ci/issues/5831
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem uninstall -aIx bundler
  - gem install bundler
  - gem update bundler
env:
# - USERNAME='WhatsARanjit'
  - PUPPET_VERSION=4.10.4
rvm:
  - 2.1.9
script:
  - 'bundle exec rake beaker'
