HOSTS:
  'master':
    pe_ver: 2017.2.1
    pe_dir: https://s3.amazonaws.com/pe-builds/released/2017.2.1
    roles:
      - master
      - dashboard
      - database
      - agent
    dist: trusty
    platform: el-7-x86_64
    box: 'puppetlabs/centos-7.2-64-nocm'
    hypervisor: vagrant
    vagrant_memsize: 4096
